### ISSUE TITLE
Problem with the train.py

### ISSUE THREAD

**Issue by antiantimatter** [crazydonkey200/tensorflow-char-rnn#16]
Hi, I've just installed and when I attempt the initial training exercise

I'm using windows/python 3.5.2/newest tensorflow

Traceback (most recent call last):
  File "train.py", line 379, in <module>
    main()
  File "train.py", line 249, in main
    train_model = CharRNN(is_training=True, use_batch=True, **params)
  File "C:\tensorflow-char-rnn\char_rnn_model.py", line 57, in __init__
    cell_fn = tf.contrib.rnn.BasicLSTMCell
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'BasicLSTMCell'

**Comment by antiantimatter** [comment]
reinstalling tensorflow fixed
