### ISSUE TITLE
'pretrained_shakespeare' cannot be sampled on TF version 1.2.1

### ISSUE THREAD

**Issue by brtkwr** [crazydonkey200/tensorflow-char-rnn#9]
Hi, I just tried to use the pretrained model and it does not seem to work on the latest version of TF. I wanted to quickly see what kind of results you get but something doesn't work. I suspect it is to do with the older version of the pretrained model not being compatible. Anyone mind sending a pull request with the latest model? My computer is a bit slow for such things at the moment. Here is the log from my OS X terminal:

```
 python sample.py --init_dir=pretrained_shakespeare --start_text="The meaning of life is" --length=10
Traceback (most recent call last):
  File "sample.py", line 114, in <module>
    main()
  File "sample.py", line 105, in main
    saver.restore(session, best_model)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: evaluation/checkpoint_saver/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_evaluation/checkpoint_saver/Const_0_0, evaluation/checkpoint_saver/RestoreV2_4/tensor_names, evaluation/checkpoint_saver/RestoreV2_4/shape_and_slices)]]

Caused by op u'evaluation/checkpoint_saver/RestoreV2_4', defined at:
  File "sample.py", line 114, in <module>
    main()
  File "sample.py", line 88, in main
    saver = tf.train.Saver(name='checkpoint_saver')
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/bharatkunwar/Anaconda3/envs/openai2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: evaluation/checkpoint_saver/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_evaluation/checkpoint_saver/Const_0_0, evaluation/checkpoint_saver/RestoreV2_4/tensor_names, evaluation/checkpoint_saver/RestoreV2_4/shape_and_slices)]]
```

**Comment by brtkwr** [comment]
Since I got impatient, I retrained the model on tensorflow 1.2.1 and have added a new pull request (https://github.com/crazydonkey200/tensorflow-char-rnn/pull/10) where sample.py runs as it should have in the first place

**Comment by crazydonkey200** [comment]
Cool, thanks for contributing :)
